// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl-Cb8dE5daAl_CeS6iwsQ7GqggZ7kKIw',
    appId: '1:128070179906:web:a3ec76c3e814066422a1db',
    messagingSenderId: '128070179906',
    projectId: 'chatgems-18642',
    authDomain: 'chatgems-18642.firebaseapp.com',
    storageBucket: 'chatgems-18642.appspot.com',
    measurementId: 'G-VZL0X4ZL7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM4Qgf8Eo7ye4ztb3d_7e2W-XZuf8ddgo',
    appId: '1:128070179906:android:e36a0570c5e4e39a22a1db',
    messagingSenderId: '128070179906',
    projectId: 'chatgems-18642',
    storageBucket: 'chatgems-18642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB11lrIUMhzcQ4p12nx9iTN8S2trrpyIYk',
    appId: '1:128070179906:ios:e224c5a55b00fa9c22a1db',
    messagingSenderId: '128070179906',
    projectId: 'chatgems-18642',
    storageBucket: 'chatgems-18642.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB11lrIUMhzcQ4p12nx9iTN8S2trrpyIYk',
    appId: '1:128070179906:ios:e224c5a55b00fa9c22a1db',
    messagingSenderId: '128070179906',
    projectId: 'chatgems-18642',
    storageBucket: 'chatgems-18642.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl-Cb8dE5daAl_CeS6iwsQ7GqggZ7kKIw',
    appId: '1:128070179906:web:843f726569cb434422a1db',
    messagingSenderId: '128070179906',
    projectId: 'chatgems-18642',
    authDomain: 'chatgems-18642.firebaseapp.com',
    storageBucket: 'chatgems-18642.appspot.com',
    measurementId: 'G-CZ0040C7EB',
  );
}
